Repository cslant/blog-docker, pull requests merged in 2024-07, with the labels that each got.

#16 Fix/clone resource
  .env.example
  README.md
  setup/resource.sh
Labels: good first issue

#17 Feature/setup docker for fe #1
  .env.example
  README.md
  docker-compose.yml
  nginx/Dockerfile
  nginx/templates/blog.cslant.com.template
  node/Dockerfile
  runner.sh
  setup/functions.sh
  setup/git.sh
  setup/tips.sh
Labels: enhancement, feature request

#20 feat: add ssl for domain blog #19
  .env.example
  .gitignore
  README.md
  docker-compose.yml
  nginx/conf/customs/.gitignore
  nginx/server/certs/.gitignore
  nginx/templates/admin.blog.cslant.com.template
  nginx/templates/api.blog.cslant.com.template
  nginx/templates/blog.cslant.com.template
  postgres/entry.d/cslant_blog.sql
  runner.sh
  setup/functions.sh
  setup/ssl.sh
Labels: feature request

#25 feat/move-db-from-docker-to-blog-storage
  blog-admin/database/cslant_blog.sql
  runner.sh
  setup/resource.sh
Labels: enhancement

#26 Fix #18 move default db
  runner.sh
  setup/resource.sh
Labels: bug

#29 feat: add docker ignore file (#22)
  .dockerignore
Labels: feature request

#31 Feature/add blog core package for admin source #30
  runner.sh
  setup/functions.sh
  setup/git.sh
  setup/resource.sh
  setup/tips.sh
  setup/variables.sh
Labels: enhancement, feature request

#28 #27 feat: add private modules for blog
  setup/git.sh
  setup/tips.sh
Labels: enhancement, feature request

#32 feat/setup-docker-elastic
  .env.example
  docker-compose.yml
  elastic/Dockerfile
Labels: enhancement

#33 Feature/update function
  README.md
  runner.sh
  setup/functions.sh
  setup/handlers.sh
  setup/tips.sh
Labels: enhancement
